# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-parking-project"
version = "1.0.0"
dependencies = [
    "sqlalchemy",
    "pymysql",
    "pandas",
    'openpyxl',
    'alibabacloud_tea_util',
    'alibabacloud_dysmsapi20170525',
    'alibabacloud_tea_openapi',
    'alibabacloud_credentials',
    'python-dotenv'
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["work_card", "temp1"]